
export interface UtilityInf {
    rooms: boolean | null,
    accessToSharedPlace: boolean | null,
    greateForRemoteWork: boolean | null,
    security: boolean | null,
    garbageShutter: boolean | null,
    backupElectricity: boolean | null,
}


export interface PropertyDetailInf {
    propertyName: string,
    phone: string,
    address: string,
    homeType: string,
    realEstateId?: string,
    yearBuilt: string,
    squareFootage: string,
    facilities: {
        numOfLivingrooms: number,
        numOfBathrooms: number,
        numOfBedrooms: number,
        numOfKitchens: number,
        numOfLibs: number,
        numOfMaidsRooms: number,
        numOfSpas: number,
        numOfStores: number,
        numOfGyms: number,
        numOfPrayerRoom: number,
    },
    parkingFeature: null,
    lotFeature: null,
    appliances: string | null,
    property: boolean | null,
    utility: UtilityInf,
    completionStatus: string | null,
    matterportLink: string | null,
    paymentProgram: string | null,
    community: {
        primarySchool: boolean,
        secondarySchool: boolean,
        collegeAndUni: boolean,
        hospital: boolean,
        supermarket: boolean,
    },
    construction: {
        ordinaryMaterial: boolean,
        uniqueMaterial: boolean
    },
    constructionCustom: string | null,
    estRentalPrice: string | null,
    govPaymentAshura: string | null,
    leasingPayment: string | null,
    conveyancingPayment: string | null,
    commission: string | null,
    images: [any, any, any, any, any],
    previewImages: [any, any, any, any, any],
    typeOfPerson: "agent" | "owner" | "none" | null,
    timeToSell: "now" | "1month" | "2-3month" | "4+month" | null,
    propertyManagment: string | null,
    sellingPrice: number | null,
    rentalPrice: number | null,
    urls: any,
    currency: "ETH" | "USA",
    cycle: "1 month" | "3 months" | "6 months" | "1 year"
    description: string
}


export const initialForm: PropertyDetailInf = {
    propertyName: "",
    phone: "",
    address: "",
    homeType: "",
    yearBuilt: "",
    squareFootage: "",
    facilities: {
        numOfLivingrooms: 0,
        numOfBathrooms: 0,
        numOfBedrooms: 0,
        numOfKitchens: 0,
        numOfLibs: 0,
        numOfMaidsRooms: 0,
        numOfSpas: 0,
        numOfStores: 0,
        numOfGyms: 0,
        numOfPrayerRoom: 0
    },
    appliances: "",
    property: null,
    utility: {
        rooms: false,
        accessToSharedPlace: false,
        greateForRemoteWork: false,
        security: false,
        garbageShutter: false,
        backupElectricity: false,
    },
    completionStatus: "",
    matterportLink: "",
    paymentProgram: "",
    community: {
        primarySchool: false,
        secondarySchool: false,
        collegeAndUni: false,
        hospital: false,
        supermarket: false,
    },
    construction: {
        ordinaryMaterial: false,
        uniqueMaterial: false
    },
    constructionCustom: "",
    estRentalPrice: "",
    govPaymentAshura: "",
    leasingPayment: "",
    conveyancingPayment: "",
    commission: "",
    images: [null, null, null, null, null],
    previewImages: [null, null, null, null, null],
    typeOfPerson: null,
    timeToSell: null,
    propertyManagment: "",
    sellingPrice: null,
    rentalPrice: null,
    urls: null,
    parkingFeature: null,
    lotFeature: null,
    currency: "ETH",
    cycle: "1 month",
    description: "",
}